### ISSUE TITLE
Burn down list for Alpha 1

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#48]
- [x] #45 - bundled protocols for the release we should operate on .netcanvas files and add JSON editing later 
- [x] #53 - associate .netcanvas files with Architect
- [x] #57 - implement name and version fields in protocol
- [x] #41 view z-index higher on editor screen
- [x] #42 #36 - update project structure and document in readme
- [x] #28 - windows install/build errors
- [x] #19 - implement system font stack
- [x] #55 - handle opening .netcanvas files from the shell.
- [x] [Help text and general missing copy](https://github.com/codaco/Architect/issues/50)
- [x] [Protocol overview panel needs to be implemented](https://github.com/codaco/Architect/issues/49)
- [x] #56 Debugging menu/shortcuts

**Comment by wwqrd** [comment]
This is now completed
