### ISSUE TITLE
[META] Manage Codebook enhancements

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#619]
There are two significant features missing from the manage codebook screen:

- [x] #603 - Add the ability to delete ego variables
- [x] #618 - Add the ability to delete node or edge types
- [ ] Make the "used in" items clickable, to route the user to the stage where the variable was used. This should close the codebook view so that cancelling from the stage returns to the timeline (not essential it does this - just a preference).
